- name: Create systemd unit template
  template:
    src: redis@.service.j2
    dest: /etc/systemd/system/redis@.service
    owner: root
    group: root
    mode: 0644
  when: redis_as_service | bool
  notify: reload systemd

- name: Reload systemd
  systemd:
    daemon_reload: yes

- name: Enable & start redis instances
  systemd:
    name: "redis@{{ item.port }}"
    enabled: yes
    state: started
  loop: "{{ redis_instances }}"
